# Services for WoT HTTP component
# Note: Actual services are dynamically registered based on Thing Description actions

# Example service definitions (these will be created dynamically):
# 
# device_123_toggle_light:
#   name: Toggle Light
#   description: Toggle the light on/off
#   fields:
#     brightness:
#       name: Brightness
#       description: Light brightness level
#       example: 50
#       selector:
#         number:
#           min: 0
#           max: 100
#           mode: slider
#
# device_123_set_temperature:
#   name: Set Temperature
#   description: Set the target temperature
#   fields:
#     temperature:
#       name: Temperature
#       description: Target temperature in Celsius
#       example: 22.5
#       selector:
#         number:
#           min: 10
#           max: 30
#           step: 0.5
#           mode: box
#           unit_of_measurement: "°C"