name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: |
        python -m venv test_env
        source test_env/bin/activate
        python -m pip install --upgrade pip

    - name: Install test dependencies
      run: |
        source test_env/bin/activate
        pip install -r requirements_test.txt

    - name: Run working tests
      run: |
        source test_env/bin/activate
        python -m pytest tests/test_basic_functionality.py tests/basic_structure_test.py tests/test_href_url_handling.py -v

    - name: Run all tests (allow failures for integration tests)
      continue-on-error: true
      run: |
        source test_env/bin/activate
        python -m pytest tests/ -v